data:
    image_size: 512 # 图像尺寸
    channels: 3 # 图像通道数
    num_workers: 0 # 数据加载的线程数
    train_data_dir: './datasets/train/'  # 训练数据集的目录路径
    test_data_dir: './datasets/test/'  # 测试数据集的目录路径
    test_save_dir: './result/'   # 保存恢复数据的目录路径
    val_save_dir: './validation/' # 保存验证数据的目录路径
    grid_r: 16 # 网格分辨率
    conditional: True # 是否使用条件生成模式

model:
    in_channels: 3 # 输入图像的通道数
    out_ch: 3 # 输出图像的通道数
    ch: 128 # 模型中的通道数
    ch_mult: [1, 2, 3, 4] # 通道数的倍数
    num_res_blocks: 2 # 残差块的数量
    attn_resolutions: [16, ] # 注意力机制的分辨率列表
    dropout: 0.0 # Dropout层的丢弃率
    ema_rate: 0.999 # 指数移动平均的速率
    ema: True # 是否使用指数移动平均
    resamp_with_conv: True # 是否使用卷积进行重采样

diffusion:
    beta_schedule: linear # beta参数的调度方式
    beta_start: 0.0001 # beta参数的初始值
    beta_end: 0.02  # beta参数的结束值
    num_diffusion_timesteps: 1000  # 扩散过程的时间步数

training:
    patch_n: 16 # 每个训练样本的裁剪块数
    batch_size: 16  # 批量训练的样本数
    n_epochs: 2000 # 训练的轮数
    n_iters: 2000000  # 每个轮次的迭代次数
    snapshot_freq: 10000   # 模型保存频率
    validation_freq: 10000 # 验证频率
    resume: './pretrained_model/diffusion_model/' # 预训练模型的路径
    seed: 1234  # 随机种子

sampling:
    batch_size: 16 # 采样时批次大小
    last_only: True # 是否只保留最后一张采样图像
    sampling_timesteps: 25 # 采样的时间步数

optim:
    weight_decay: 0.000 # 权重衰减
    optimizer: "Adam" # 优化器名称
    lr: 0.00002 # 学习率
    amsgrad: False # 是否使用 AMSGrad 优化器
    eps: 0.00000001 # 优化器的 epsilon 值
